- lambda function
- NumPy
- Random Module

### lambda function

- A lambda function is small anonymous function.
- A lambda function can take any number of arguments,but can only have one expression. 

#### syntax:

In [1]:
# example1

m=lambda a:a**2

print(m(3))

9


In [2]:
#example2


ankita=lambda a,b,c:a+b+c

print(ankita(3,5,6))

14


In [3]:


a1=10
a2=20

print(a1+a2)

30


### lambda function with no arguments

In [4]:
x=lambda :print('Hello Python')

x()

Hello Python


### lambda with more than one arguments

In [5]:
m=lambda a,b,c:a+b+c

print(m(1,2,3))

6


- map()
- filter()
- reduce()

### map()

#### The map() function iterates through all items in the given iterable and excute the function.

In [7]:
#example
# output in bool

k1=['Ankita','Priya','Avani','Nidhi']
a3=map(lambda t1:t1[4]=='i',k1)
print(list((a3)))

[False, False, True, True]


### filter()

#### filter() forms a new list that contains only elements that satisfy a certain condition.

In [9]:
m1= ['Apple','Banana','Orange','Apricot']

v=filter(lambda x:x[3]=='i',m1)

print(list(v))

['Apricot']


### reduce()

- its work differently than map(),filter()
- its returns a single value

In [10]:
# library

from functools import reduce

In [11]:
lst=[2,3,4,5,6,4,5,6]

print(reduce(lambda x,y:x+y,lst))

35


In [12]:
#########################################################################################################

## NumPy

- NumPy is a python library used for working with array
- It mostly work with numerical data

In [13]:
#importing numpy library

import numpy as np

### check version

In [14]:
np.__version__

'1.23.5'

### 0(zero) dimensional array

In [15]:
k1=np.array(2045)

k1

array(2045)

In [16]:
type(k1)

numpy.ndarray

In [17]:
# check array dimension 

In [19]:
np.ndim(k1)

0

### One dimensional array

In [20]:
k2=np.array([1,2,3,4,5,6,7,4,5,6,6,7,7,4])

k2

array([1, 2, 3, 4, 5, 6, 7, 4, 5, 6, 6, 7, 7, 4])

In [21]:
type(k2)

numpy.ndarray

In [22]:
np.ndim(k2)

1

### two dimensional array

In [23]:
k3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
k3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
np.ndim(k3)

2

### --------------------------------------------------------------------------------------------------------

### Array Sclicing

In [26]:
array1 = [1,2,3,4,5,6,7,8,9,10]

In [27]:
array1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
#-- example

In [29]:
array1[5:7]

[6, 7]

In [30]:
array1[2:5]

[3, 4, 5]

In [31]:
array1[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [32]:
array1[2:]

[3, 4, 5, 6, 7, 8, 9, 10]

In [33]:
array1[::3]

[1, 4, 7, 10]

### indexing

In [34]:
array1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
#example

In [36]:
array1[2]

3

In [37]:
array1[9]

10

### Array creation using zero

In [38]:
f1 = np.zeros([4,6],dtype=int)

f1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
type(f1)

numpy.ndarray

In [40]:
f2 = np.zeros([4,6],int)

f2

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [41]:
np.ndim(f2)

2

### Array creation using ones(1)

In [42]:
f3 = np.ones([6,6],int)

f3

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### Array creation using full

In [43]:
f4 =np.full([3,6],100)

f4

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [ ]:
-