In [ ]:
- Random Module
  - randint()
  - randrange()
  - choice()
  - shuffle()
  - random()
  - sample()

- where and abs() function
- concatenate,stack,split,array_split()


- user define function

- reshape
- arange


### Random Module

Python Random module is an in-built module of Python which is used to generate random numbers.

#### randint()

returns a random number between the given range

In [ ]:
#syntax:
randint(start,end-1,step)

In [47]:
import numpy as np
# example

np.random.randint(1,6)

5

### randrange()

In [179]:
#syntax

#randrange(start,end)           both include

import random

print(random.randrange(3, 9))

5


### choice()

In [57]:
# example

lst=('apple','banana','cherry')

print(random.choice(lst))

apple


#### shuffle()

In [66]:
lst1=['apple','banana','cherry']

random.shuffle(lst1)
lst1

['cherry', 'apple', 'banana']

#### random()

- Returns a random float number between 0 and 1
- no parameter

In [69]:
print(random.random())

0.8627715409809458


#### sample()

In [92]:
import random

lst= (11,34,56,56,67,57,7,9)

random.sample(lst,3)

[7, 9, 67]

### numpy arithmethic function

- add
- subtract
- multiply
- devide
- power

In [93]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.add(a, b)
print(result)


[5 7 9]


In [97]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.add(a, b)
print(result)

[5 7 9]


### subtract

In [99]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])

c1 = np.subtract(b1,a1) 

print(c1)

[3 3 3]


### multiply

In [100]:
a3= np.array([1, 2, 3])
b3 = np.array([4, 5, 6])

In [101]:
a3

array([1, 2, 3])

In [102]:
b3

array([4, 5, 6])

In [103]:
f1=np.multiply(a3,b3)

f1

array([ 4, 10, 18])

### power

In [106]:
a4 = np.array([1, 2, 3])
b4 = np.array([4, 5, 6])

result1 = np.power(a4, b4)
print(result1)

[  1  32 729]


### arange

In [117]:
# np.arange(start,end-1,step)


x1 =np.arange(1,51)
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### reshape()

In [124]:
x2 = np.arange(1,11).reshape(5,2)
x2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [123]:
x2 = np.arange(1,11)
x2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### abs()

In [ ]:
- it return absolute value

In [125]:
#example


s=-10
abs(s)

10

### concatenate

In [126]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[10,20,30,40],[50,60,70,80]])

n3=np.concatenate([n1,n2])
n3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

In [133]:
n=np.array([[1,2,3,4],[5,6,7,8]])
m=np.array([[10,20,30,40],[50,60,70,80]])

t=np.concatenate([n,m],axis=1)
t

array([[ 1,  2,  3,  4, 10, 20, 30, 40],
       [ 5,  6,  7,  8, 50, 60, 70, 80]])

### stack

In [139]:
a=np.array([1,2,3,4])

b=np.array([5,6,7,8])

v=np.stack((a,b))
v


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [140]:
np.ndim(a)

1

In [141]:
np.ndim(v)

2

### split()

In [150]:
g1=np.arange(1,11)

g1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
g1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
np.split(g1,7)

ValueError: array split does not result in an equal division

### array_split()

In [162]:
g2=np.arange(1,31)
g2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [164]:
np.array_split(g2,10)

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8, 9]),
 array([10, 11, 12]),
 array([13, 14, 15]),
 array([16, 17, 18]),
 array([19, 20, 21]),
 array([22, 23, 24]),
 array([25, 26, 27]),
 array([28, 29, 30])]

### where()

In [187]:
# example:



w1 = np.array([10,20,30,40,50])

w2 = np.array([60,70,80,90,100])


w3=np.where(w1>20,w1,w2)

w3

array([60, 70, 30, 40, 50])

In [186]:
w1>20

array([False, False,  True,  True,  True])

In [ ]:
False:second array elements
True : first array elements   
    

In [ ]:
###############################################################################################################

### User defined function

In [ ]:
- in built

   example:print,type,max,min,
        
        
 - user define function 

  def

In [190]:
#syntax:

def function_name(arg1,arg2, ...):
    
    statements
  return


#calling function

addition()

30

In [ ]:
#example

def addition():
    a=10
    b=20
    c=a+b
    return c


#calling function

addition()

#### function with no arguments

In [193]:
def welcome():
    print('Hello python')
    

welcome()   

Hello python


#### function with arguments

In [194]:
def multiply(num1,num2):
    m=num1*num2
    return m

In [197]:
multiply(4,3)

12

In [198]:
multiply(8,7)

56

In [ ]:
*args

**kwargs

In [199]:
# examples


def abc(*n):
    for i in n:
        print(i)
        
        
abc(1,2,3,4,5,6,7,8,9,10)       

1
2
3
4
5
6
7
8
9
10


In [201]:
def multiply1(*n1):
    m1=n1*n1
    return m1

multiply(2,5,4,3)

TypeError: multiply() takes 2 positional arguments but 4 were given

In [ ]:
def add(*var):
    result=0
    for i in var:
        result=result+i
    print(result)

In [ ]:
add(1,2,100,7)

In [ ]:
num=int(input('enter a number :'))